### PR TITLE
Add JobCleaner timeout dynamically

### PR DESCRIPTION
**Pull request by PumpkinSeed**
Suggested implementation of #575

### CODE REVIEW

**Comment by bgentry** [comment]
@PumpkinSeed thanks for taking a stab at this! I think we will end up needing to add some test coverage for it, but otherwise it looks pretty much spot on.

Could you please add yourself to the CLA here before we move forward on this? https://github.com/riverqueue/rivercla

**Comment by PumpkinSeed** [comment]
@bgentry I wrote a specific test for this case.

I already did the CLA in the past.

**Comment by bgentry** [comment]
D’oh, sorry I missed that 🤦🏼‍♂️ newborn sleep deprivation kicking in over here 😅 Will sync with @brandur on this shortly and hopefully get it merged, thank you!

**Comment by bgentry** [comment]
Hi @PumpkinSeed, really sorry about the delay on this. I should be able to get it merged today and shipped in the next release.

**Comment by bgentry** [comment]
@brandur I did some cleanup on this one and I think it should be suitable for now, but please feel free to take a look before it ships!

**Review by bgentry — APPROVED** [review]

**Pull request merged**
