### PR TITLE
ci: Use setup-sqlc@v4 action

### PR DESCRIPTION
**Pull request by andrewmbenton**
Just noticed that your sqlc workflow would be simpler with the [setup-sqlc GitHub action](https://github.com/sqlc-dev/setup-sqlc).

### CODE REVIEW

**Comment by brandur** [comment]
@andrewmbenton Thanks!

Would you mind doing a no-op `git commit --amend` and force pushing again? Something odd seems to have happened with the GitHub Actions checks here — they're still in limbo an hour later and GitHub is not currently reporting any status events.

**Comment by bgentry** [comment]
@brandur I think we might need to approve this first for a first-time contributor before the actions will run
Screenshot 2023-11-28 at 8 18 23 PM

**Review by bgentry — APPROVED** [review]

**Comment by brandur** [comment]
@bgentry So I have this feature on for other repos too, but usually there's an "approve CI run" button you can press. I'm not sure if I'm blind or there's a bug somewhere, but I'm not seeing it anywhere in my UI. Do you see it?

**Comment by bgentry** [comment]
I've been looking everywhere to find a setting that will make that button show up, afaict all the settings look correct but I don't see any way to approve the workflow per [the docs](https://docs.github.com/en/actions/managing-workflow-runs/approving-workflow-runs-from-public-forks#approving-workflow-runs-on-a-pull-request-from-a-public-fork) 😖

**Comment by brandur** [comment]
WTH. I think it might be a bug ... I've seen the button hundreds of times before. It's just not here right now.

**Comment by bgentry** [comment]
@brandur I think we might need the `pull_request` trigger on the CI workflow: https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#pull-request-events-for-forked-repositories

**Comment by brandur** [comment]
@bgentry Doh. Okay NM, I guess that's it. Good idea to actually RTFM.

**Comment by bgentry** [comment]
Thank you @andrewmbenton 🙏

**Comment by andrewmbenton** [comment]
> Thank you @andrewmbenton 🙏

Happy to help work out the configuration kinks early on.

**Pull request merged**
