### PR TITLE
Added an argument type for river.AddWorker

### PR DESCRIPTION
**Pull request by vacoo**
Снимок экрана 2024-07-19 в 10 25 01

### CODE REVIEW

**Comment by brandur** [comment]
@vacoo That type parameter will be inferred from the compiler. You can see working code here that's confirmed to be correct by the test suite:

https://github.com/riverqueue/river/blob/master/example_insert_and_work_test.go#L51

It looks like you've got a different problem somewhere. Your tooltip seems to be saying about `NextRetry`. Do you want to see if something weird is going on there?

**Comment by vacoo** [comment]
> @vacoo That type parameter will be inferred from the compiler. You can see working code here that's confirmed to be correct by the test suite:
> 
> https://github.com/riverqueue/river/blob/master/example_insert_and_work_test.go#L51
> 
> It looks like you've got a different problem somewhere. Your tooltip seems to be saying about `NextRetry`. Do you want to see if something weird is going on there?

The NextRetry method is already available in river.WorkerDefaults.

**Comment by brandur** [comment]
> The NextRetry method is already available in river.WorkerDefaults.

Yep, I know. Are you sure you don't have any additional customization?

**Comment by vacoo** [comment]
> > The NextRetry method is already available in river.WorkerDefaults.
> 
> Yep, I know. Are you sure you don't have any additional customization?

I don't think so. I use go land and go1.22.5 darwin/arm64
Снимок экрана 2024-07-19 в 10 45 32

**Comment by brandur** [comment]
Hm, maybe check whether the code compiles outside Goland with `go build .`?

If that doesn't work, then maybe you could try copying the code from the example test just in case there's a typo or something somewhere:

https://github.com/riverqueue/river/blob/master/example_insert_and_work_test.go

**Comment by vacoo** [comment]
> Hm, maybe check whether the code compiles outside Goland with `go build .`?
> 
> If that doesn't work, then maybe you could try copying the code from the example test just in case there's a typo or something somewhere:
> 
> https://github.com/riverqueue/river/blob/master/example_insert_and_work_test.go

Strangely, everything works. It just seems to be just a warning

**Comment by brandur** [comment]
Ah weird. Possibly a GoLand issue somewhere ...

**Pull request closed without merging**
